### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [vadim01er/javaCubePolitech#1]
1. - [x] Зачем Вам переменная `m` в первом конструкторе, нельзя вместо неё использовать `i`?
2. - [x] В конструкторе из трехмерного массива Вы никак не проверяете этот массив. Проверить корректность расположения цветов, действительно, достаточно сложно, но проверьте хотя бы размеры массивов граней.
3. - [x] В том же конструкторе Вы используете метод `clone()` для копирования содержимого массива, но этот метод реализует так называемое поверхностное копирование. То есть копируется только внешний трехмерный массив, а все двухмерные массивы (грани) не копируются, а остаются ссылками на исходные массивы и могут быть случайно испорчены извне.
4. - [x] Если конструктор из трехмерного массива оправдан необходимостью задавать начальное состояние кубика, то метод `setSide` явно некорректен по своей сути. Меняя одну грань, Вы переводите Ваш объект в некорректное состояние, поскольку нельзя, поменяв только одну грань, из одного корректного состояния получить другое. Кроме того, (как раз вследствие этой некорректности) мне даже не придумать ситуацию, в которой нужно поменять одну грань кубика. Начальное задание кубика, как у Вас в тестах, куда как правильнее делать через конструктор.
5. - [x] Судя по всему, методы `rotateLeft` и `rotateRight` можно было сделать нестатическими и передавать в них не массив, а название грани.
6. - [x] Аналогичное замечание про поверхностное копирование в `clone` в методе `getCubeNow`.
7. - [x] Не совсем понятно назначение метода `search`.
8. - [x] В `equals` желательно явно проверить на `null`.
9. - [x] В `Arrays` есть не только `deepHashCode`, но и `deepEquals`, которым можно воспользоваться для сравнения трехмерных массивов.
10. - [x] Сейчас в `equals` переменная `coincides` бессмысленна, можно просто проверять `res1`. Другое дело, что в у Тимофея (с которым Вы как минимум советовались, судя по похожести ваших решений) эта переменная использовалась, чтобы не пропускать последующие повороты кубика. А сейчас у Вас кубик, переданный в `equals`, если он равен первому, внезапно поворачивается таким же образом, как первый, хотя `equals` менять ничего не должен ни в одном из сравниваемых объектов.
11. - [ ] Ваш `hashCode` сейчас работает неправильно, так как даёт разные значения в зависимости от того, как повёрнут кубик, в то время как `equals` для таких кубиков вернёт `true`.

**Comment by vadim01er** [comment]
Я реализовал все кроме 11, не знаю как сделать это

**Comment by maximpetrov** [comment]
1. Вы зачем-то (видимо, по совету Idea) конструкторы и часть методов сделали package-private, что в этой ситуации некорректно. Они должны быть публичными, иначе воспользоваться ими можно будет только в этом же пакете (то есть в Вашем случае только в тестах).
1. Почему бы не объединить проверку размеров переданного массива и копирование элементов?
1. В том же конструкторе и ещё в двух местах Вы неправильно копируете массивы: первая размерность должна быть 6, а не `size`.
1. Копирование массива в `equals` лишнее, ведь Вы передаёте этот массив в конструктор, где снова его копируете.
1. В `equals` можно убрать ещё один цикл с помощью `deepEquals` (зачем проверять каждую грань, если можно сравнить сразу трехмерный массив)
1. Проверка на `null` в `equals` должна работать не так. Если переданный объект `null`, то `equals` должен просто вернуть `false`.
1. Метод `toStringOneBrink` либо должен возвращать строку, либо называться `printOneBrink`.
1. Замечание про `hashCode` остаётся в силе.

**Comment by maximpetrov** [comment]
1. Пункт 5 в силе. Тем более, что там баг и фактически сравнивается только последняя грань.
1. Пункт 8 тоже в силе. Вы ничего не поменяли (или даже сделали хуже), просто реализовав `deepHashCode` руками.

**Comment by vadim01er** [comment]
я просто не знаю как реализовать hashCode, там очень много вариантов как можно расположить кубик и не знаю к какому мне именно находить hashCode. Я бы  с радостью бы это исправил если бы знал.

**Comment by maximpetrov** [comment]
Как я уже говорил, я тоже не могу однозначно сказать, как лучше в Вашей ситуации сделать `hashCode`, это зависит от контекста, в котором будет использоваться Ваш класс (если бы Вы писали его для реальной задачи). Вполне возможно, что такое сложное сравнение не нужно или выгода от обнаружения случаев равенства с поворотом меньше, чем затраты на такое сравнение при каждом повороте. Если так, то Ваш `hashCode` сгодился бы, но нужно было бы переделать `equals`. Если равенство с поворотом нужно, то, как один из вариантов, `hashCode` тоже можно сделать с поворотами. То есть посчитать для каждого из вариантов поворота хэш-код через `deepHashCode`, а потом их все сложить. Тогда, вроде бы, хэш-коды двух равных с поворотом кубиков должны быть равны, так как у них будет одинаковый набор состояний (поворотов) в разном порядке, но от перестановки мест слагаемых, сумма не меняется. Не уверен, что такой сложный метод вычисления хеш-кода хорош для использования в каких-нибудь алгоритмических задачах, но он по крайней мере будет соответствовать контракту.

В любом случае, можете оставить как есть, будем считать задание зачтённым.
